backend:

  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img"

collections:

  - name: "pages"
    label: "Pages"
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: "home"
        file: "index.md"
        label: "Éditer la page d'accueil"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan 1", name: "slogan1", widget: "string"}
          - {label: "Slogan 2", name: "slogan2", widget: "string"}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Texte du lien couverture", name: "cover_link_text", widget: "string"}
          - {label: "Lien couverture", name: "cover_link", widget: "string"}
          - {label: "Titre d'introduction", name: "intro_title", widget: "string"}
          - {label: "Texte d'introduction", name: "intro_text", widget: "markdown"}
          - {label: "Titre de l'évènement", name: "event_title", widget: "string"}
          - {label: "Jours de l'évènement", name: "event_days", widget: "string"}
          - {label: "Heures de l'évènement", name: "event_time", widget: "string"}
          - {label: "Endroit de l'évènement", name: "event_location", widget: "string"}
          - {label: "Lien évènement", name: "event_link", widget: "string"}
          - {label: "Texte du lien évènement", name: "event_link_text", widget: "string"}
          - {label: "Titre de l'horaire", name: "horaire_title", widget: "string"}
          - {label: "Slogan de l'horaire", name: "horaire_slogan", widget: "string"}
          - {label: "Titre Intervenants", name: "intervenants_title", widget: "string"}
      - name: "home"
        file: "intervenants.md"
        label: "Éditer la page Intervenants"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan 1", name: "slogan1", widget: "string"}
          - {label: "Slogan 2", name: "slogan2", widget: "string"}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - label: "Profile"
            name: "profile"
            widget: "object"
            fields:
              - {label: "Public", name: "public", widget: "boolean", default: true}
              - {label: "Name", name: "name", widget: "string"}
              - label: "Birthdate"

          - label: "Gallery"
            name: "galleryImages"
            widget: "list"
            field:
              - {label: Image, name: image, widget: image}
