backend:

  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img"

collections:

  - name: "pages"
    label: "Pages"
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: "home"
        file: "index.md"
        label: "Éditer la page d'accueil"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan 1", name: "slogan1", widget: "string"}
          - {label: "Slogan 2", name: "slogan2", widget: "string"}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Texte du lien couverture", name: "cover_link_text", widget: "string"}
          - {label: "Lien couverture", name: "cover_link", widget: "string"}
          - {label: "Titre d'introduction", name: "intro_title", widget: "string"}
          - {label: "Texte d'introduction", name: "intro_text", widget: "markdown"}
          - {label: "Titre de l'évènement", name: "event_title", widget: "string"}
          - {label: "Jours de l'évènement", name: "event_days", widget: "string"}
          - {label: "Heures de l'évènement", name: "event_time", widget: "string"}
          - {label: "Endroit de l'évènement", name: "event_location", widget: "string"}
          - {label: "Addresse de l'évènement (ligne 1)", name: "event_address_1", widget: "string", required: false}
          - {label: "Addresse de l'évènement (ligne 2)", name: "event_address_2", widget: "string", required: false}
          - {label: "Lien évènement", name: "event_link", widget: "string"}
          - {label: "Texte du lien évènement", name: "event_link_text", widget: "string"}
          - {label: "Titre de l'horaire", name: "horaire_title", widget: "string"}
          - {label: "Slogan de l'horaire", name: "horaire_slogan", widget: "string"}
          - {label: "Titre Intervenants", name: "intervenants_title", widget: "string"}
          - {label: "Titre Réservations", name: "reservation_title", widget: "string"}
          - label: "Réservations Boîte 1"
            name: "reservation_box_1"
            widget: "object"
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Prix", name: "price", widget: "string"}
              - {label: "Prix (sous-texte)", name: "subtext", widget: "string"}
              - label: "Liste des forfaits inclus"
                name: "features"
                widget: "list"
                fields:
                  - {label: Description, name: desc, widget: string}
          - label: "Réservations Boîte 2"
            name: "reservation_box_2"
            widget: "object"
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Prix", name: "price", widget: "string"}
              - {label: "Prix (sous-texte)", name: "subtext", widget: "string"}
              - label: "Liste des forfaits inclus"
                name: "features"
                widget: "list"
                fields:
                  - {label: Description, name: desc, widget: string}

      - name: "intervenants"
        file: "intervenants.md"
        label: "Éditer la page Intervenants"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan 1", name: "slogan1", widget: "string", required: false}
          - {label: "Slogan 2", name: "slogan2", widget: "string", required: false}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - label: "Intervenants"
            name: "intervenants"
            widget: "list"
            fields:
              - {label: Nom, name: name, widget: string}
              - {label: Photo, name: image, widget: image}
              - {label: Titre/poste, name: job, widget: string}
              - {label: Compagnie/Entreprise, name: company, widget: string}
              - {label: Lien vers vidéo, name: video, widget: string}
              - label: "Conférences"
                name: "conferences"
                widget: "list"
                fields:
                  - {label: Nom, name: name, widget: string}
                  - {label: Date, name: date, widget: string}
              - {label: Biographie, name: bio, widget: markdown}
      - name: "conferences"
        file: "conferences.md"
        label: "Éditer la page Conférences"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan 1", name: "slogan1", widget: "string", required: false}
          - {label: "Slogan 2", name: "slogan2", widget: "string", required: false}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - label: "Horaire"
            name: "schedules"
            widget: "list"
            fields:
              - {label: Heure, name: time, widget: string}
              - {label: Titre, name: title, widget: string}
              - label: "Intervenants"
                name: "intervenants"
                widget: "list"
                fields:
                  - {label: Photo, name: image, widget: image}
                  - {label: Nom, name: name, widget: string}
                  - {label: Compagnie, name: company, widget: string}
                  - {label: Journées, name: days, widget: string}
              - {label: Description, name: desc, widget: markdown}


      - name: "a-propos"
        file: "a-propos.md"
        label: "Éditer la page À propos"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan 1", name: "slogan1", widget: "string", required: false}
          - {label: "Slogan 2", name: "slogan2", widget: "string", required: false}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Titre d'introduction", name: "intro_title", widget: "string"}
          - {label: "Texte d'introduction", name: "intro_text", widget: "markdown"}
          - {label: "Titre Thématiques", name: "thematiques_title", widget: "string"}
          - {label: "Texte Thématiques", name: "thematiques_text", widget: "markdown"}
          - label: "Thématique"
            name: "thematiques"
            widget: "list"
            fields:
              - {label: Titre, name: title, widget: string}
              - {label: Icône (Font Awesome), name: icon, widget: string}
              - {label: Texte, name: text, widget: string}

          - {label: "Titre Chiffres", name: "facts_title", widget: "string"}
          - {label: "Image Chiffres", name: "facts_bg", widget: "image"}
          - label: "Chiffres"
            name: "facts"
            widget: "list"
            fields:
              - {label: Chiffre, name: number, widget: string}
              - {label: Icône (Font Awesome), name: icon, widget: string}
              - {label: Texte, name: desc, widget: string}

      - name: "inscriptions"
        file: "inscriptions.md"
        label: "Éditer la page Inscriptions"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan 1", name: "slogan1", widget: "string", required: false}
          - {label: "Slogan 2", name: "slogan2", widget: "string", required: false}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: "Texte", name: "body", widget: "markdown"}
          - label: "Journées"
            name: "days"
            widget: "list"
            fields:
              - {label: Journée, name: day, widget: string}
          - label: "Types"
            name: "types"
            widget: "list"
            fields:
              - {label: Type, name: type, widget: string}

  - name: "settings"
    label: "Paramètres du site"
    delete: false # Prevent users from deleting documents in this collection
    editor:
     preview: false
    files:
       - name: "general"
         label: "Général"
         file: "_data/settings.yml"
         description: "Paramètres Généraux"
         fields:
           - {label: "Titre du site", name: "site_title", widget: "string"}
           - {label: "Courriel de contact", name: "site_email", widget: "string", required: false}
           - {label: "Numéro de téléphone de contact", name: "site_tel", widget: "string", required: false}
           - {label: "Logo du site", name: "site_logo", widget: "image", required: false}
           - {label: "Adresse (ligne 1)", name: "site_address_1", widget: "string", required: false}
           - {label: "Adresse (ligne 2)", name: "site_address_2", widget: "string", required: false}
           - {label: "Lien vers page Facebook", name: "url_facebook", widget: "string", required: false}
           - {label: "Lien vers page Instagram", name: "url_instagram", widget: "string", required: false}
           - {label: "Lien vers page Twitter", name: "url_twitter", widget: "string", required: false}
           - {label: "Lien vers page Youtube", name: "url_youtube", widget: "string", required: false}

       - name: "navigation"
         label: "Navigation"
         file: "_data/navigation.yml"
         description: "Navigation du site"
         fields:
          - label: "Liens navigation"
            name: main_nav
            widget: list
            required: false
            fields:
              - {label: Titre, name: title, widget: string}
              - {label: URL, name: url, widget: string}
